MaxFitness/Blog/urls.py
from django.urls import path
from . import views

# www.maxfit.com/blog/

app_name = 'Blog'

urlpatterns = [
    path('',views.blog_home,name='blog_app'),
    path('blog-page/<int:blog_id>/',views.view_blog,name='view_blog'),
    path('add-new-blog/',views.add_blog,name='add_new_blog'),
    path('delete-blog/<int:blog_id>/',views.delete_blog,name='delete_blog'),
    path('update-blog/<int:blog_id>/',views.update_blog,name='update_blog'),
    path('login/',views.login_user,name='login_user'),
    path('signup/',views.signup_user,name='signup_user'),
    path('dashboard/',views.user_dashboard,name='dashboard'),
    path('logout/',views.logout_user,name='logout_user'),
]

MaxFitness/MaxFitness/urls.py
from django.contrib import admin
from django.urls import path,include
from . import settings
from . import views
from django.conf.urls.static import static

urlpatterns = [
    path('',views.home, name='home_page'),
    path('blog/',include('Blog.urls')),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MaxFitness/Blog/models.py
from django.db import models

# Create your models here.


class Blogger(models.Model):
    blogger_id = models.AutoField(primary_key=True, unique=True)
    first_name = models.CharField(max_length=300)
    last_name = models.CharField(max_length=300)
    email = models.EmailField(unique=True)
    country = models.CharField(max_length=300)
    city = models.CharField(max_length=300)
    profile_picture = models.ImageField(upload_to='bloggers_profiles/',
                                         default='bloggers_profiles/default.avif')
    password = models.CharField(max_length=3000,editable=False)

    def __str__(self):
        return f'Blogger ID: {self.blogger_id}, First Name: {self.first_name}, Last Name: {self.last_name}'


class Blog(models.Model):

    CATEGORY_CHOICES = [
        ('Weight Loss', 'Weight Loss'),
        ('Weight Gain', 'Weight Gain'),
        ('Food', 'Food'),
        ('Health', 'Health'),
        ('Yoga', 'Yoga'),
        ('Muscle Gain', 'Muscle Gain'),
    ]

    blog_id = models.AutoField(primary_key=True, unique=True)
    title = models.CharField(max_length=3000)
    category = models.CharField(max_length=300,choices=CATEGORY_CHOICES)
    introduction = models.TextField(max_length=6000)
    sub_heading1 = models.CharField(max_length=1000)
    content1 = models.TextField(max_length=10000)
    sub_heading2 = models.CharField(max_length=1000)
    content2 = models.TextField(max_length=10000)
    sub_heading3 = models.CharField(max_length=1000)
    content3 = models.TextField(max_length=10000)
    sub_heading4 = models.CharField(max_length=1000)
    content4 = models.TextField(max_length=10000)
    post_date = models.DateTimeField(auto_now=True)
    published_by = models.ForeignKey(Blogger,on_delete=models.CASCADE,null=True)

    def __str__(self):
        return f'Blog ID: {self.blog_id}, category: {self.category}'

MaxFitness/Blog/views.py
from django.shortcuts import render,HttpResponse,redirect
from . import models
from django.db import IntegrityError
from django.db.models import Q
import random
from django.contrib.auth.hashers import make_password,check_password

# Create your views here.

def blog_home(request):
    if request.GET:
        user_query = request.GET.get('user_query')
        blogs = models.Blog.objects.filter(Q(title__icontains=user_query) | Q(introduction__icontains=user_query)
                                      | Q(sub_heading1__icontains=user_query) | Q(sub_heading2__icontains=user_query)
                                      | Q(sub_heading3__icontains=user_query) | Q(sub_heading4__icontains=user_query)).all()
    else:       
        '''Select * from blogs;'''
        blogs = models.Blog.objects.select_related('published_by').all()
    data = {
        'blogs': blogs,
        'random_number': random.randint(1,6)
    }
    return render(request, 'Blog/blogs.html',context=data)

def add_blog(request):
    if not request.session.get('blogger_id'):
        return redirect('Blog:login_user')
    
    if request.method == 'POST':

        msg = {}

        title = request.POST.get('title')
        category = request.POST.get('category')
        introduction = request.POST.get('introduction')
        sub_heading1 = request.POST.get('sub_heading1')
        sub_heading2 = request.POST.get('sub_heading2')
        sub_heading3 = request.POST.get('sub_heading3')
        sub_heading4 = request.POST.get('sub_heading4')
        content1 = request.POST.get('content1')
        content2 = request.POST.get('content2')
        content3 = request.POST.get('content3')
        content4 = request.POST.get('content4')

        if all([title,category,introduction,sub_heading1,sub_heading2,sub_heading3,sub_heading4,
                content1,content2,content3,content4]):
            
            blogger_id = request.session.get('blogger_id')
            blogger = models.Blogger.objects.get(blogger_id=blogger_id)

            models.Blog.objects.create(title=title,category=category,introduction=introduction,
                                       sub_heading1=sub_heading1,sub_heading2=sub_heading2,sub_heading3=sub_heading3,
                                       sub_heading4=sub_heading4,content1=content1,content2=content2,content3=content3,
                                       content4=content4,published_by=blogger)

            msg['success'] = 'New Blog Created Successfully.'
        else:
            msg['error'] = 'All Fields Are Required.'
        
        return render(request, 'Blog/add_blog.html', msg)


    return render(request, 'Blog/add_blog.html')

def view_blog(request,blog_id):
    '''Select * from blogs where blog_id = blog_id;'''
    blog = models.Blog.objects.get(blog_id=blog_id)
    data = {
        'blog': blog
    }
    return render(request, 'Blog/view_blog.html',context=data)

def delete_blog(request,blog_id):
    if not request.session.get('blogger_id'):
        return redirect('Blog:login_user')
    '''Delete from blogs where blog_id = blog_id;'''
    # blog = models.Blog.objects.get(blog_id=blog_id)
    # blog.delete()
    return redirect('Blog:blog_app')

def update_blog(request,blog_id):
    if not request.session.get('blogger_id'):
        return redirect('Blog:login_user')
    
    '''Update blogs set cols=vals where blog_id = blog_id'''
    blog = models.Blog.objects.get(blog_id=blog_id)
    data = {'blog': blog}
    if request.method == 'POST':

        title = request.POST.get('title')
        category = request.POST.get('category')
        introduction = request.POST.get('introduction')
        sub_heading1 = request.POST.get('sub_heading1')
        sub_heading2 = request.POST.get('sub_heading2')
        sub_heading3 = request.POST.get('sub_heading3')
        sub_heading4 = request.POST.get('sub_heading4')
        content1 = request.POST.get('content1')
        content2 = request.POST.get('content2')
        content3 = request.POST.get('content3')
        content4 = request.POST.get('content4')

        if all([title,category,introduction,sub_heading1,sub_heading2,sub_heading3,sub_heading4,
                content1,content2,content3,content4]):
            try:
                blog.title = title
                blog.category = category
                blog.introduction = introduction
                blog.sub_heading1 = sub_heading1
                blog.sub_heading2 = sub_heading2
                blog.sub_heading3 = sub_heading3
                blog.sub_heading4 = sub_heading4
                blog.content1 = content1
                blog.content2 = content2
                blog.content3 = content3
                blog.content4 = content4
                blog.save()

                data['success'] = 'Blog Updated Successfully.'
            except IntegrityError as e:
                data['error'] = str(e)
        else:
            data['error'] = 'All Fields Are Required.'

    return render(request,'Blog/update.html',context=data)

def login_user(request):
    if request.method == 'POST':
        msg = {}

        email = request.POST.get('email')
        password = request.POST.get('password')

        if all([email, password]):
            is_valid_email = models.Blogger.objects.filter(email=email).exists()
            if is_valid_email:
                blogger = models.Blogger.objects.get(email=email)
                is_valid_password = check_password(password,blogger.password)
                if is_valid_password:
                    request.session['blogger_id'] = blogger.blogger_id
                    request.session['profile_photo'] = blogger.profile_picture.url
                    return redirect('home_page')
                else:
                    msg['error'] = 'Your Email Or Password is Incorrect.'
            else:
                msg['error'] = 'Your Email Or Password is Incorrect.'
        else:   
            msg['error'] = 'All Fields Are Required.'
        return render(request,'Blog/login.html',context=msg)
    return render(request,'Blog/login.html')

def signup_user(request):
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')
        country = request.POST.get('country')
        city = request.POST.get('city')
        password = request.POST.get('password')
        confirm_password = request.POST.get('confirm-password')

        msg = {}

        
        if all([first_name, last_name, email, country, city, password, confirm_password]):
            if password == confirm_password:
                try : 
                    profile_photo = request.FILES.get('profile_photo')

                    encrypted_password = make_password(password)

                    new_blogger = models.Blogger()
                    new_blogger.first_name = first_name
                    new_blogger.last_name = last_name
                    new_blogger.email = email
                    new_blogger.country = country
                    new_blogger.city = city
                    new_blogger.password = encrypted_password

                    if profile_photo:
                        new_blogger.profile_picture = profile_photo
                    
                    new_blogger.save()
                    msg['success'] = 'User Created Successfully.'

                except IntegrityError as e:
                    msg['error'] = str(e)
            else:
                msg['error'] = 'Passwords Do Not Matched'
        else:
            msg['error'] = 'All Fields Are Required'

        return render(request,'Blog/signup.html',context=msg)
    
    return render(request,'Blog/signup.html')

def logout_user(request):
    if request.session.get('blogger_id'):
        del request.session['blogger_id']
        del request.session['profile_photo']
    return redirect('home_page')

def user_dashboard(request):
    if request.session.get('blogger_id'):
        blogger_id = request.session.get('blogger_id')

        blogger = models.Blogger.objects.get(blogger_id=blogger_id)

        """select count(*) from Blogs where published_by = blogger_id"""

        number_of_blogs = models.Blog.objects.filter(published_by=blogger_id).count()

        """select * from blogs inner join bloggers on blogs.published_by = bloggers.blogger_id
        where blogs.published_by = bloggers.blogger_id"""

        blogger_blogs = models.Blog.objects.select_related('published_by').filter(published_by=blogger_id).all()

        data = {
            'blogger': blogger,
            'number_of_blogs':number_of_blogs,
            'blogger_blogs':blogger_blogs
        }



        return render(request,'Blog/user_dashboard.html',context=data)
    else:
        return redirect('Blog:login_user')

MaxFitness/Blog/templates/Blog/add_blog.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Add New Blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
</head>
  <body>
    {% include 'navbar.html' %}
    <main>
        <div class="top-heading">
            <h1 class="text-center m-5">Add New Blog</h1>
        </div>
        <div class="rounded border p-5 mb-5 bg-body-secondary container">
            {% if success %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>Success : </strong> {{success}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}
            {% if error %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <strong>Error : </strong> {{error}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}
            <form action="{% url 'Blog:add_new_blog' %}" method="Post">
                {% csrf_token %}
                <div class="form-floating mb-3">
                    <input type="text" name="title" class="form-control" id="floatingInput" placeholder="name@example.com">
                    <label for="floatingInput">Title</label>
                </div>
                <div >
                    <select name="category" class="form-select form-select mb-3" aria-label="Large select example">
                        <option selected>Select Blog Category</option>
                        <option value="Weight Loss">Weight Loss</option>
                        <option value="Weight Gain">Weight Gain</option>
                        <option value="Food">Food</option>
                        <option value="Health">Health</option>
                        <option value="Muscle Gain">Muscle Gain</option>
                        <option value="Yoga">Yoga</option>
                    </select>
                </div>
                <div class="form-floating mb-3">
                    <textarea name="introduction" class="form-control" placeholder="Leave a comment here" id="floatingTextarea2" style="height: 250px"></textarea>
                    <label for="floatingTextarea2">Introduction</label>
                </div>
                <div class="form-floating mb-3">
                    <input name="sub_heading1" type="text" class="form-control" id="floatingInput" placeholder="name@example.com">
                    <label for="floatingInput">Sub Heading</label>
                </div>
                <div class="form-floating mb-3">
                    <textarea name="content1" class="form-control" placeholder="Leave a comment here" id="floatingTextarea2" style="height: 350px"></textarea>
                    <label for="floatingTextarea2">Content</label>
                </div>
                <div class="form-floating mb-3">
                    <input name="sub_heading2" type="text" class="form-control" id="floatingInput" placeholder="name@example.com">
                    <label for="floatingInput">Sub Heading</label>
                </div>
                <div class="form-floating mb-3">
                    <textarea name="content2" class="form-control" placeholder="Leave a comment here" id="floatingTextarea2" style="height: 350px"></textarea>
                    <label for="floatingTextarea2">Content</label>
                </div>
                <div class="form-floating mb-3">
                    <input name="sub_heading3" type="text" class="form-control" id="floatingInput" placeholder="name@example.com">
                    <label for="floatingInput">Sub Heading</label>
                </div>
                <div class="form-floating mb-3">
                    <textarea name="content3" class="form-control" placeholder="Leave a comment here" id="floatingTextarea2" style="height: 350px"></textarea>
                    <label  for="floatingTextarea2">Content</label>
                </div>
                <div class="form-floating mb-3">
                    <input name="sub_heading4" type="text" class="form-control" id="floatingInput" placeholder="name@example.com">
                    <label for="floatingInput">Sub Heading</label>
                </div>
                <div class="form-floating mb-3">
                    <textarea name="content4" class="form-control" placeholder="Leave a comment here" id="floatingTextarea2" style="height: 350px"></textarea>
                    <label for="floatingTextarea2">Content</label>
                </div>
                <button type="submit" class="btn btn-dark w-100 mb-3">Post</button>
            </form>
        </div>
    </main>
    {% include 'footer.html' %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

MaxFitness/Blog/templates/Blog/blogs.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blogs</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'Blog/css/blogs.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
</head>

<body>
    {% include 'navbar.html' %}
    <main class="main-div">
        <div class="blog-list">
            {% for blog in blogs %}
            <div class="card">
                <div class="thumbnail"><img class="left" src="{% static 'Blog/img/blog1.jpg' %}"/></div>
                <div class="right">
                  <h1><a href="{% url 'Blog:view_blog' blog_id=blog.blog_id %}">{{blog.title}}</a></h1>
                  <span class="author">{{blog.category}}</span>
                  <div class="separator"></div>
                  <p>{{ blog.introduction|slice:":300" }}...</p>
                </div>
                <div>
                  <h5>{{blog.post_date|date:"d"}}</h5>
                  <h6>{{blog.post_date|date:"M Y"}}</h6>
                </div>
                <div class="fab"><img src="{{blog.published_by.profile_picture.url}}" alt=""><span>{{blog.published_by.first_name}} {{blog.published_by.last_name}}</span></div>
              </div>
              {% endfor %}
          </div>
          <div class="filter-list">
              <h1>Filters</h1>
              <div class="filter-container">
                <form class="mt-4">
                  <div class="col-md-4 w-100 mb-2">
                    <label for="inputState" class="form-label">Category</label>
                    <select id="inputState" class="form-select">
                      <option selected>Choose...</option>
                      <option value="Weight Loss">Weight Loss</option>
                        <option value="Weight Gain">Weight Gain</option>
                        <option value="Food">Food</option>
                        <option value="Food">Health</option>
                        <option value="Food">Muscle Gain</option>
                        <option value="Food">Yoga</option>
                    </select>
                  </div>
                  <div class="col-md-4 w-100 mb-2">
                    <label for="inputState" class="form-label">Select By Publisher</label>
                    <select id="inputState" class="form-select">
                      <option selected>Choose...</option>
                      <option value="Weight Loss">Weight Loss</option>
                        <option value="Weight Gain">Weight Gain</option>
                        <option value="Food">Food</option>
                        <option value="Food">Health</option>
                        <option value="Food">Muscle Gain</option>
                        <option value="Food">Yoga</option>
                    </select>
                  </div>
                  <div class="col-md-4 w-100 mt-4 mb-3">
                    <div class="row">
                      <div class="col">
                        <input type="radio" class="btn-check" name="options-base" id="option5" autocomplete="off" checked>
                        <label class="btn" for="option5">Ascending</label>  
                      </div>
                      <div class="col">
                        <input type="radio" class="btn-check" name="options-base" id="option6" autocomplete="off">
                        <label class="btn" for="option6">Descending</label>
                      </div>
                    </div>
                  </div>
                  <button type="submit" class="btn btn-primary w-100">Apply</button>
                </form>
                
              </div>
          </div>
        </main>
    
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
      </body>
    </html>
    
    

MaxFitness/Blog/templates/Blog/login.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
  </head>
  <body>
    <nav>
      {% include 'navbar.html' %}
    </nav>
    <main>
        <h1 class="text-center text-dark mt-5 m-3">LOGIN</h1>
        <div class="container w-50">
            {% if error %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <strong>Error : </strong> {{error}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}
            <form class="rounded p-4 mb-5 border w-80" action="{% url 'Blog:login_user' %}" method="post">
                {% csrf_token %}
                <div class="form-floating mb-3">
                    <input type="email" name="email" class="form-control" id="floatingInput" placeholder="name@example.com">
                    <label for="floatingInput">Email address</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password">
                    <label for="floatingPassword">Password</label>
                </div>
                <div class="mb-3">
                    <button type="submit" class="btn btn-dark w-100">Login</button>
                </div>
            </form>
        </div>
        </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

MaxFitness/Blog/templates/Blog/signup.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Signup</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">

  </head>
  <body>
    <nav>
      {% include 'navbar.html' %}
    </nav>
    <main>
        <h1 class="text-center text-dark mt-5 m-3">SIGN UP</h1>
        <div class="container w-50">
            {% if success %}
                <div class="alert alert-success alert-dismissible fade show" role="alert">
                    <strong>Success : </strong> {{success}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}
            {% if error %}
                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                    <strong>Error : </strong> {{error}}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endif %}
            <form class="rounded p-4 mb-5 border w-80" enctype="multipart/form-data" action="{% url 'Blog:signup_user' %}" method="post">
                {% csrf_token %}
                <div class="form-floating mb-3">
                    <div class="row g-2">
                        <div class="col-md">
                            <div class="form-floating">
                                <input type="text" name="first_name" class="form-control" id="floatingInputGrid" placeholder="First Name">
                                <label for="floatingInputGrid">First Name</label>
                            </div>
                        </div>
                        <div class="col-md">
                            <div class="form-floating">
                                <input type="text" name="last_name" class="form-control" id="floatingInputGrid" placeholder="Last Name">
                                <label for="floatingInputGrid">Last Name</label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-floating mb-3">
                    <input type="email" name="email" class="form-control" id="floatingInput" placeholder="name@example.com">
                    <label for="floatingInput">Email address</label>
                </div>
                <div class="form-floating ">
                    <div class="row g-2">
                        <div class="col-md">
                            <div class="form-floating">
                                <input type="text" name="country" class="form-control" id="floatingInputGrid" placeholder="First Name">
                                <label for="floatingInputGrid">Country</label>
                            </div>
                        </div>
                        <div class="col-md">
                            <div class="form-floating">
                                <input type="text" name="city" class="form-control" id="floatingInputGrid" placeholder="Last Name">
                                <label for="floatingInputGrid">City</label>
                            </div>
                        </div>
                    </div>
                </div>
                <label for="floatingInputGrid" class="mt-1 mb-1 text-end w-100">(Optional)</label>
                <div class="form-floating mb-3">
                    <div class="input-group mb-3">
                        <label class="input-group-text bg-dark text-white" for="inputGroupFile01">Profile Photo</label>
                        <input name="profile_photo" type="file" class="form-control" id="inputGroupFile01">
                    </div>
                </div>
                <div class="form-floating mb-3">
                    <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password">
                    <label for="floatingPassword">Password</label>
                </div>
                <div class="form-floating mb-3">
                    <input type="password" name="confirm-password" class="form-control" id="floatingPassword" placeholder="Password">
                    <label for="floatingPassword">Confirm Password</label>
                </div>
                <div class="mb-3">
                    <button type="submit"  class="btn btn-dark w-100">Sign up</button>
                </div>
            </form>
        </div>
        </div>
    </main>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

MaxFitness/Blog/templates/Blog/view_blog.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Blog</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'Blog/css/view_blog.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <style>
        .blog-header {
            background-image: url("{% static 'Blog/img/blog1.jpg' %}");
            background-size: cover;
        }
        .edit-delete{
            display: flex;
            justify-content: center;
        }
        .edit-delete a{
            width: 40%;
            margin: 10px;
        }
    </style>
  </head>
  <body>
      {% include 'navbar.html' %}

    <main>
        <div class="blog-header">
            <H1>{{blog.title}}</H1>
        </div>
        <div class="edit-delete">
            {% if request.session.blogger_id %}

                {% if request.session.blogger_id == blog.published_by.blogger_id %}

                    <a href="{% url 'Blog:delete_blog' blog_id=blog.blog_id %}" class="btn btn-danger">Delete</a>
                    <a href="{% url 'Blog:update_blog' blog_id=blog.blog_id %}" class="btn btn-success">Edit</a>
            
                {% endif %}
            {% endif %}
        </div>
        <div class="blog-content mt-5 mb-5 container">
            <h3>Introduction</h3>
            <p>{{blog.introduction}}</p>
            <h3>{{blog.sub_heading1}}</h3>
            <p>{{blog.content1}}</p>
            <h3>{{blog.sub_heading2}}</h3>
            <p>{{blog.content2}}</p>
            <h3>{{blog.sub_heading3}}</h3>
            <p>{{blog.content3}}</p>
            <h3>{{blog.sub_heading4}}</h3>
            <p>{{blog.content4}}</p>
        </div>
    </main>
    </body>
</html>