MaxFitness/Blog/urls.py
from django.urls import path
from . import views

# www.maxfit.com/blog/

app_name = 'Blog'

urlpatterns = [
    path('',views.blog_home,name='blog_app'),
    path('blog-page/<int:blog_id>/',views.view_blog,name='view_blog'),
    path('add-new-blog/',views.add_blog,name='add_new_blog'),
    path('delete-blog/<int:blog_id>/',views.delete_blog,name='delete_blog'),
    path('update-blog/<int:blog_id>/',views.update_blog,name='update_blog'),
    path('login/',views.login_user,name='login_user'),
    path('signup/',views.signup_user,name='signup_user'),
    path('dashboard/',views.user_dashboard,name='dashboard'),
    path('logout/',views.logout_user,name='logout_user'),
]

MaxFitness/MaxFitness/urls.py
from django.contrib import admin
from django.urls import path,include
from . import settings
from . import views
from django.conf.urls.static import static

urlpatterns = [
    path('',views.home, name='home_page'),
    path('blog/',include('Blog.urls')),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MaxFitness/templates/footer.html
    <article id="wrap">
    <article id="lightings">
        <section id="one">
                <section id="two">
                    <section id="three">
                        <section id="four">
                            <section id="five">
                 
                            </section>
                        </section>
                    </section>
                </section>
        </section>
        </article>
    </article>

MaxFitness/templates/home.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Home</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/footer.css' %}">

  <link rel="stylesheet" href="{% static 'css/home.css' %}">
  <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
</head>

<body>
  {% include 'navbar.html' %}
  <h4 class="text-center pt-3">Letest Blogs</h4>
  <main>
    <div class="blog-list">
      {% for blog in blogs %}
      <div class="card">
        <div class="thumbnail"><img class="left" src="{% static 'Blog/img/blog1.jpg' %}" /></div>
        <div class="right">
          <h1><a href="{% url 'Blog:view_blog' blog_id=blog.blog_id %}">{{blog.title}}</a></h1>
          <span class="author">{{blog.category}}</span>
          <div class="separator"></div>
          <p>{{ blog.introduction|slice:":300" }}...</p>
        </div>
        <div>
          <h5>{{blog.post_date|date:"d"}}</h5>
          <h6>{{blog.post_date|date:"M Y"}}</h6>
        </div>
        <div class="fab"><img
            src="https://img.freepik.com/free-vector/blue-circle-with-white-user_78370-4707.jpg?size=338&ext=jpg&ga=GA1.1.1297763733.1729555200&semt=ais_hybrid"
            alt=""><span>Harry Potter</span></div>
      </div>
      {% endfor %}
    </div>
    </div>
  </main>

  {% include 'footer.html' %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
</body>

</html>

MaxFitness/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">MaxFitness</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'home_page' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'Blog:blog_app' %}">Blogs</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="#">About-Us</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="#">Contact-Us</a>
                </li>
            </ul>
            <form class="d-flex" method="GET" action="{% url 'Blog:blog_app' %}" role="search">
                <input name="user_query" class="form-control me-2" type="search" placeholder="Search"
                    aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
        {% if request.session.blogger_id %}
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 profile-menu">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    <div class="profile-pic">
                        <img src="{{request.session.profile_photo}}" alt="Profile Picture">
                    </div>
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{% url 'Blog:add_new_blog' %}"><i class="fas fa-cog fa-fw"></i> Add New Blog</a>
                    </li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="{% url 'Blog:dashboard' %}"><i class="fas fa-sliders-h fa-fw"></i>
                            Account</a></li>
                    <li><a class="dropdown-item" href="#"><i class="fas fa-cog fa-fw"></i> Settings</a></li>
                    <li>
                        <hr class="dropdown-divider">
                    </li>
                    <li><a class="dropdown-item" href="{% url 'Blog:logout_user' %}"><i class="fas fa-sign-out-alt fa-fw"></i> Log Out</a>
                    </li>
                </ul>
            </li>
        </ul>
        {% else %}
            <a href="{% url 'Blog:login_user' %}" class="btn btn-outline-primary ms-2">Login</a>
            <a href="{% url 'Blog:signup_user' %}" class="btn btn-primary ms-2">Signup</a>
        {% endif %}
    </div>
    </div>
</nav>